Do not use boost/functional/hash.hpp
I believe this issue is caused by a compiler bug in clang.

error: implicit instantiation of undefined template
'std::__1::hash<Kmer>'

See bcgsc/abyss#37