Specify std::hash explicitly
The default template argument for the hash function does not seem to
work. I believe this issue is caused by a compiler bug in clang.

error: implicit instantiation of undefined template
'std::__1::hash<cstring>'

error: implicit instantiation of undefined template
'std::__1::hash<Kmer>'

Closes bcgsc/abyss#37