FastaRecord: Initialize the member variable anchor
Fix the error:
In file included from ../../KAligner/KAligner.cpp:5:0:
../../DataLayer/FastaReader.h: In member function 'std::pair<T, long unsigned int>
PipeMux<T>::nextValue() [with T = FastaRecord]':
../../DataLayer/FastaReader.h:123:8: error: '<anonymous>.FastaRecord::anchor'
is used uninitialized in this function [-Werror=uninitialized]