CircleCI: Use clang 5.0 on Ubuntu 18.04 LTS (Bionic Beaver) (#196)
* abyss-fixmate: Fix error: quick_erase is deprecated

quick_erase() is no longer necessary with BOOST 1.48.0.
quick_erase() is deprecated with BOOST 1.65.0.
See http://www.boost.org/doc/libs/1_65_0/doc/html/unordered/changes.html

Fixes https://github.com/bcgsc/abyss/issues/173

* CircleCI: Use Ubuntu 18.04 LTS (Bionic Beaver)

* Bloom/bloom.cc: Fix an error with GCC 7

Fix the error:
error: this statement may fall through [-Werror=implicit-fallthrough=]
dieWithUsageError();

* Konnector/konnector.h: Add a missing break statement

* FastaRecord: Initialize the member variable anchor

Fix the error:
In file included from ../../KAligner/KAligner.cpp:5:0:
../../DataLayer/FastaReader.h: In member function 'std::pair<T, long unsigned int>
PipeMux<T>::nextValue() [with T = FastaRecord]':
../../DataLayer/FastaReader.h:123:8: error: '<anonymous>.FastaRecord::anchor'
is used uninitialized in this function [-Werror=uninitialized]

* Common/SAM.h: Fix error: this statement may fall through