Fix bogus ambiguous overloaded operator '!=' error
I believe this issue is caused by a compiler bug in clang.

error: use of overloaded operator '!=' is ambiguous
(with operand types 'Matches::reverse_iterator'
(aka 'reverse_iterator<iterator>') and 'reverse_iterator'
(aka 'reverse_iterator<iterator>'))
it != matches.rend(); ++it)

Closes bcgsc/abyss#40