Supress incorrect unused typedef warnings
error: typedef 'savalue_type' locally defined but not used
[-Werror=unused-local-typedefs]
typedef typename std::iterator_traits<sarray_type>::value_type
savalue_type;

See bcgsc/abyss#26