Fix unused typedef compiler warnings
In function 'void find_complex_transitive_edges(Graph&, OutIt)':
Graph/GraphAlgorithms.h:118:
error: typedef 'edge_property_type' locally defined but not used

In function 'void processQuery(std::vector<Alignment>&, Graph&)':
Scaffold/longseqdist.cpp:90:39:
error: typedef 'VP' locally defined but not used