Remove unused typedef
Fix the compiler warnings of GCC 4.8.

error: typedef 'vertex_descriptor' locally defined but not used
[-Werror=unused-local-typedefs]
typedef typename Graph::vertex_descriptor vertex_descriptor;

Closes bcgsc/abyss#26